# Generated by Django 6.1.1 on 2026-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_author_category_alter_livro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='livros', to='biblioteca.author'),
        ),
    ]
