# Generated by Django 6.1.1 on 2026-10-09 18:24

from django.db import migrations

def copiar_dados_autor_many(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')
    for livro in Livro.objects.all():
        if livro.autor:
            livro.autor_many.add(livro.autor)
            
def reverter_many(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')
    for livro in Livro.objects.all():
        primeiro_autor = livro.autor_many.first()
        if primeiro_autor:
            livro.autor = primeiro_autor
            livro.save()

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_livro_autor_many'),
    ]

    operations = [
        migrations.RunPython(copiar_dados_autor_many, reverter_many)
    ]
