# Generated by Django 6.1.1 on 2026-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20261009_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='biblioteca.author'),
        ),
    ]
